language: rust
dist: trusty
sudo: required

addons:
  apt:
    sources:
    - sourceline: 'ppa:0k53d-karl-f830m/openssl'
    packages:
    - libssl-dev

rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
