[package]
name = "euphonium"
version = "0.1.0"
authors = ["SAPikachu <sapikachu@gmail.com>"]
description = "Recursive DNS resolver"
keywords = ["dns", "recursive", "mioco"]
license = "MPL-2.0"
homepage = "https://github.com/SAPikachu/euphonium"
repository = "https://github.com/SAPikachu/euphonium"
readme = "README.md"

[dependencies]
clippy = "*"
mioco = { git = "https://github.com/dpc/mioco.git" }
mio = "*"
env_logger = "*"
trust-dns = "0.5.*"
quick-error = "1.0.*"
rand = "0.3.*"
log = "*"
byteorder = "0.5.*"
itertools = "*"
newtype_derive = "0.1.*"
custom_derive = "0.1.*"
serde = { version = "^0.7", features = ["nightly"] }
serde_macros = "^0.7"
serde_yaml = "^0.2"
