[package]
name = "euphonium"
version = "0.1.0"
authors = ["SAPikachu <sapikachu@gmail.com>"]

[dependencies]
clippy = "*"
mioco = { git = "https://github.com/dpc/mioco.git" }
mio = "*"
env_logger = "*"
trust-dns = "0.5.*"
quick-error = "1.0.*"
rand = "0.3.*"
log = "*"
byteorder = "0.5.*"
