[package]
authors = ["SAPikachu <sapikachu@gmail.com>"]
description = "Recursive DNS resolver"
homepage = "https://github.com/SAPikachu/euphonium"
keywords = ["dns", "recursive", "mioco"]
license = "MPL-2.0"
name = "euphonium"
readme = "README.md"
repository = "https://github.com/SAPikachu/euphonium"
version = "0.1.0"

[dependencies]
byteorder = "0.5.*"
chrono = "0.2.22"
custom_derive = "0.1.*"
docopt = "0.6.80"
docopt_macros = "0.6.84"
env_logger = "*"
itertools = "*"
log = "*"
mio = "*"
newtype_derive = "0.1.*"
parking_lot = "^0.2.5"
quick-error = "1.0.*"
rand = "0.3.*"
rustc-serialize = "^0.3.19"
serde_json = "^0.7.0"
serde_macros = "^0.7"
serde_yaml = "^0.2"
treebitmap = "^0.2"
trust-dns = "^0.7.1"
yaml-rust = "^0.3.3"
openssl = "^0.7.14"
lazy_static = "*"

[dependencies.clippy]
optional = true
version = "*"

[dependencies.mioco]
git = "https://github.com/dpc/mioco.git"

[dependencies.serde]
features = ["nightly"]
version = "^0.7"

[features]
default = ["clippy"]

[lib]
name = "eulib"
path = "src/lib.rs"
