[package]
authors = ["SAPikachu <sapikachu@gmail.com>"]
description = "Recursive DNS resolver"
homepage = "https://github.com/SAPikachu/euphonium"
keywords = ["dns", "recursive", "mioco"]
license = "MPL-2.0"
name = "euphonium"
readme = "README.md"
repository = "https://github.com/SAPikachu/euphonium"
version = "0.1.0"

[dependencies]
byteorder = "0.5.*"
chrono = "0.2.22"
docopt = { git = "https://github.com/docopt/docopt.rs.git" }
docopt_macros = { git = "https://github.com/docopt/docopt.rs.git" }
env_logger = "*"
itertools = "*"
log = "*"
macro-attr = "*"
mio = "*"
mioco = "*"
newtype_derive = "0.1.*"
parking_lot = "^0.2.5"
quick-error = "1.0.*"
rand = "*"
rustc-serialize = "*"
serde = "^1.0"
serde_json = "*"
serde_yaml = "^0.7"
serde_derive = "*"
treebitmap = { git = "https://github.com/sopium/treebitmap.git" }
trust-dns = "^0.7.1"
yaml-rust = "*"
openssl = "^0.7.14"
lazy_static = "*"
timebomb = { git = "https://github.com/SAPikachu/timebomb.git" } 

[replace]
"serde_yaml:0.7.0" = { git = "https://github.com/SAPikachu/serde-yaml.git" }

[lib]
name = "eulib"
path = "src/lib.rs"
