[package]
name = "euphonium"
version = "0.1.0"
authors = ["SAPikachu <sapikachu@gmail.com>"]

[dependencies]
mioco = "0.4.*"
env_logger = "*"
trust-dns = "0.5.*"
quick-error = "1.0.0"
rand = "0.3.*"
log = "*"
